name: three_words_a_day
description: 하루 세 말씀 - Flutter MVP
environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.3
  intl: ^0.19.0
  provider: ^6.1.2 # (간단/가벼운 상태관리. 원하면 Riverpod로 교체 가능)
  scrollable_positioned_list: ^0.3.8

flutter:
  uses-material-design: true
  assets:
    - assets/db/bible_krv_sample.sqlite
